/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DefaultApiFactory } from "./api";
import { Configuration } from "./configuration";

export const api = DefaultApiFactory(new Configuration({
    basePath: "http://0.0.0.0:8000",
    baseOptions: { headers: { "Authorization": "0338333a490f1ddf27477cd5295731618a4265eb2655bd7a4f36c5fdd9ad1337.HEsztDrxY85zuW2l/eJCcnrz+LLrBlayJezVhDHjFb0ncuLcbRDs96+zUcWvzCnGo3U=" } }
}));
