/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DefaultApiFactory } from "./api";
import { Configuration } from "./configuration";
const API_BASE_URL = import.meta.env.VITE_SERVER_API_BASE_URL || 'http://localhost:8000';

console.log(API_BASE_URL);
let res = await DefaultApiFactory(new Configuration({
    basePath: API_BASE_URL
})).generateKeypairGenerateKeypairGet();

export const api = DefaultApiFactory(new Configuration({
    basePath: API_BASE_URL,
    baseOptions: {
        credentials: 'include',
        headers: {
            'Content-Type': 'application/json',
            "Authorization": res.data.access_token,
        }
    }
}));
